# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-02 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='no_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
