# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-02 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_area_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='rating',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='area',
            name='user1',
        ),
    ]
